export const CARD_DESIGNS = [
  // ══════════════════════════════
  // INICIACIÓN — 5 subniveles
  // ══════════════════════════════
  {
    id: 'nivel1_verde',
    nombre: 'EL DEBUT',
    nivel: 1,
    background: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800&q=80',
    color: '#00ee55',
    colorSecundario: '#00ffaa',
    fondo: ['#001208', '#001a0d', '#000e06', '#000804'],
    borde: '#00ee55',
    decoracion: null,
    efectos: [],
    bloqueado: false,
    requisito: null,
  },
  {
    id: 'nivel1_azul',
    nombre: 'EL HAMBRE',
    nivel: 1,
    background: 'https://images.unsplash.com/photo-1518604666860-9ed391f76460?w=800&q=80',
    color: '#0099ff',
    colorSecundario: '#44ccff',
    fondo: ['#000818', '#000d22', '#00060f', '#000308'],
    borde: '#0099ff',
    decoracion: null,
    efectos: [],
    bloqueado: false,
    requisito: null,
  },
  {
    id: 'nivel1_bronce',
    nombre: 'EL RITMO',
    nivel: 1,
    background: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
    color: '#dd8833',
    colorSecundario: '#ffaa55',
    fondo: ['#130800', '#1a0d00', '#0d0500', '#080300'],
    borde: '#dd8833',
    decoracion: null,
    efectos: [],
    bloqueado: false,
    requisito: null,
  },
  {
    id: 'nivel1_plata',
    nombre: 'EL DEPREDADOR',
    nivel: 1,
    background: 'https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80',
    color: '#cccccc',
    colorSecundario: '#ffffff',
    fondo: ['#0a0a0a', '#111111', '#080808', '#050505'],
    borde: '#cccccc',
    decoracion: null,
    efectos: [],
    bloqueado: false,
    requisito: null,
  },
  {
    id: 'nivel1_oro',
    nombre: 'EL VETERANO',
    nivel: 1,
    background: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80',
    color: '#ffcc00',
    colorSecundario: '#ffee88',
    fondo: ['#110e00', '#181200', '#0d0a00', '#080600'],
    borde: '#ffcc00',
    decoracion: null,
    efectos: [],
    bloqueado: false,
    requisito: null,
  },

  // ══════════════════════════════
  // COMPETIDOR — 5 subniveles
  // ══════════════════════════════
  {
    id: 'nivel2_inicio',
    nombre: 'EL CONTENDIENTE',
    nivel: 2,
    subnivel: 'inicio',
    color: '#4488FF',
    colorSecundario: '#88BBFF',
    fondo: ['#020A2A', '#0A2060', '#0D3AAE'],
    borde: '#4488FF',
    decoracion: null,
    efectos: [],
    nivel2Variant: 'inicio',
    bloqueado: true,
    requisito: 'Completa 3 logros de Competidor I',
    progreso_key: 'pj',
    progreso_meta: 10,
  },
  {
    id: 'nivel2_bronce',
    nombre: 'EL CENTENARIO',
    nivel: 2,
    subnivel: 'bronce',
    color: '#CC6622',
    colorSecundario: '#FF9944',
    fondo: ['#180800', '#3A1600', '#5A2800'],
    borde: '#CC6622',
    decoracion: null,
    efectos: [],
    nivel2Variant: 'bronce',
    bloqueado: true,
    requisito: 'Completa 3 logros de Competidor II',
    progreso_key: 'pj',
    progreso_meta: 10,
  },
  {
    id: 'nivel2_plata',
    nombre: 'EL IMPARABLE',
    nivel: 2,
    subnivel: 'plata',
    color: '#AAAACC',
    colorSecundario: '#DDDDEE',
    fondo: ['#0A0A14', '#222230', '#3A3A4A'],
    borde: '#AAAACC',
    decoracion: null,
    efectos: [],
    nivel2Variant: 'plata',
    bloqueado: true,
    requisito: 'Completa 3 logros de Competidor III',
    progreso_key: 'pj',
    progreso_meta: 10,
  },
  {
    id: 'nivel2_oro',
    nombre: 'EL DOMINADOR',
    nivel: 2,
    subnivel: 'oro',
    color: '#FFCC00',
    colorSecundario: '#FFE840',
    fondo: ['#140E00', '#382800', '#5A4000'],
    borde: '#FFCC00',
    decoracion: null,
    efectos: [],
    nivel2Variant: 'oro',
    bloqueado: true,
    requisito: 'Completa 3 logros de Competidor IV',
    progreso_key: 'pj',
    progreso_meta: 10,
  },
  {
    id: 'nivel2_legendario',
    nombre: 'EL CAMPEADOR',
    nivel: 2,
    subnivel: 'legendario',
    color: '#00CC66',
    colorSecundario: '#00FF88',
    fondo: ['#060010', '#0E0028', '#1A0040'],
    borde: '#00CC66',
    decoracion: null,
    efectos: [],
    nivel2Variant: 'legendario',
    bloqueado: true,
    requisito: 'Completa 3 logros de Competidor V',
    progreso_key: 'pj',
    progreso_meta: 10,
  },

  // ══════════════════════════════
  // ÉLITE — 5 subniveles
  // ══════════════════════════════
  {
    id: 'nivel3_inicio',
    nombre: 'EL ELEGIDO',
    nivel: 3,
    subnivel: 'inicio',
    color: '#4488FF',
    colorSecundario: '#88BBFF',
    fondo: ['#020A2A', '#0A2060', '#0D3AAE'],
    borde: '#4488FF',
    decoracion: null,
    efectos: [],
    nivel3Variant: 'inicio',
    bloqueado: true,
    requisito: 'Completa 3 logros de Élite I',
    progreso_key: 'pj',
    progreso_meta: 25,
  },
  {
    id: 'nivel3_bronce',
    nombre: 'EL MAESTRO',
    nivel: 3,
    subnivel: 'bronce',
    color: '#CC6622',
    colorSecundario: '#FF9944',
    fondo: ['#180800', '#3A1600', '#5A2800'],
    borde: '#CC6622',
    decoracion: null,
    efectos: [],
    nivel3Variant: 'bronce',
    bloqueado: true,
    requisito: 'Completa 3 logros de Élite II',
    progreso_key: 'pj',
    progreso_meta: 25,
  },
  {
    id: 'nivel3_plata',
    nombre: 'EL INTOCABLE',
    nivel: 3,
    subnivel: 'plata',
    color: '#AAAACC',
    colorSecundario: '#DDDDEE',
    fondo: ['#0A0A14', '#222230', '#3A3A4A'],
    borde: '#AAAACC',
    decoracion: null,
    efectos: [],
    nivel3Variant: 'plata',
    bloqueado: true,
    requisito: 'Completa 3 logros de Élite III',
    progreso_key: 'pj',
    progreso_meta: 25,
  },
  {
    id: 'nivel3_oro',
    nombre: 'EL FENÓMENO',
    nivel: 3,
    subnivel: 'oro',
    color: '#FFCC00',
    colorSecundario: '#FFE840',
    fondo: ['#140E00', '#382800', '#5A4000'],
    borde: '#FFCC00',
    decoracion: null,
    efectos: [],
    nivel3Variant: 'oro',
    bloqueado: true,
    requisito: 'Completa 3 logros de Élite IV',
    progreso_key: 'pj',
    progreso_meta: 25,
  },
  {
    id: 'nivel3_legendario',
    nombre: 'LA MÁQUINA',
    nivel: 3,
    subnivel: 'legendario',
    color: '#00CC66',
    colorSecundario: '#00FF88',
    fondo: ['#060010', '#0E0028', '#1A0040'],
    borde: '#00CC66',
    decoracion: null,
    efectos: [],
    nivel3Variant: 'legendario',
    bloqueado: true,
    requisito: 'Completa 3 logros de Élite V',
    progreso_key: 'pj',
    progreso_meta: 25,
  },

  // ══════════════════════════════
  // LEYENDA — 5 subniveles
  // ══════════════════════════════
  {
    id: 'premium_inicio',
    nombre: 'EL INMORTAL',
    nivel: 6,
    subnivel: 'inicio',
    color: '#D6B65D',
    colorSecundario: '#F4E6A1',
    fondo: ['#0D2B8E', '#091F7A', '#071660', '#040E40'],
    borde: 'gradiente_negro_oro',
    decoracion: null,
    efectos: [],
    premium: true,
    premiumVariant: 'inicio',
    bloqueado: true,
    requisito: 'Completa 3 logros de Leyenda I',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
  {
    id: 'premium_bronce',
    nombre: 'EL HISTÓRICO',
    nivel: 6,
    subnivel: 'bronce',
    color: '#C88830',
    colorSecundario: '#E8C070',
    fondo: ['#112870', '#0C2055', '#081840', '#050E3A'],
    borde: 'gradiente_negro_oro',
    decoracion: null,
    efectos: [],
    premium: true,
    premiumVariant: 'bronce',
    bloqueado: true,
    requisito: 'Completa 3 logros de Leyenda II',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
  {
    id: 'premium_plata',
    nombre: 'EL MITO',
    nivel: 6,
    subnivel: 'plata',
    color: '#B0C8FF',
    colorSecundario: '#E0EEFF',
    fondo: ['#182EA0', '#1030A0', '#0C2070', '#060A38'],
    borde: 'gradiente_diamante',
    decoracion: null,
    efectos: [],
    premium: true,
    premiumVariant: 'plata',
    bloqueado: true,
    requisito: 'Completa 3 logros de Leyenda III',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
  {
    id: 'premium_oro',
    nombre: 'EL ETERNO',
    nivel: 6,
    subnivel: 'oro',
    color: '#F8E460',
    colorSecundario: '#FFF8C0',
    fondo: ['#1A3CB8', '#1238A8', '#0C2480', '#06103C'],
    borde: 'gradiente_negro_oro',
    decoracion: null,
    efectos: [],
    premium: true,
    premiumVariant: 'oro',
    bloqueado: true,
    requisito: 'Completa 3 logros de Leyenda IV',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
  {
    id: 'premium_legendario',
    nombre: 'LA LEYENDA',
    nivel: 6,
    subnivel: 'legendario',
    color: '#FFF5A0',
    colorSecundario: '#FFFFFF',
    fondo: ['#2040D0', '#1640C8', '#0E2890', '#080844'],
    borde: 'gradiente_negro_oro',
    decoracion: null,
    efectos: [],
    premium: true,
    premiumVariant: 'legendario',
    bloqueado: true,
    requisito: 'Completa 3 logros de Leyenda V',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
]

export const NIVEL_NOMBRES = {
  1: 'INICIACIÓN',
  2: 'COMPETIDOR',
  3: 'ÉLITE',
  4: 'ORO',
  5: 'ÉLITE',
  6: 'LEYENDA',
}

export const NIVEL_COLORES = {
  1: '#00ddd0',
  2: '#cd7f32',
  3: '#c0c0c0',
  4: '#ffd700',
  5: '#9955ff',
  6: '#ff8800',
}
