export const CARD_DESIGNS = [

  // ══════════════════════════════
  // NIVEL 1 — NORMAL (gratis)
  // ══════════════════════════════
  {
    id: 'normal_teal',
    nombre: 'CLÁSICA',
    nivel: 1,
    background: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80',
    color: '#00ddd0',
    colorSecundario: '#9955ff',
    fondo: ['#00e8d8', '#009ecc', '#1558e2', '#110450'],
    borde: '#00ddd0',
    decoracion: null,
    efectos: ['ondas_suaves'],
    bloqueado: false,
    requisito: null,
  },
  {
    id: 'normal_azul',
    nombre: 'OCÉANO',
    nivel: 1,
    color: '#2299ee',
    colorSecundario: '#0044aa',
    fondo: ['#001830', '#002a50', '#003870', '#001020'],
    borde: '#2299ee',
    decoracion: null,
    efectos: ['ondas_suaves', 'rayas_diagonales'],
    bloqueado: false,
    requisito: null,
  },
  {
    id: 'normal_verde',
    nombre: 'CAMPO',
    nivel: 1,
    color: '#00e87a',
    colorSecundario: '#00aa55',
    fondo: ['#001a0e', '#002a18', '#003a22', '#000e08'],
    borde: '#00e87a',
    decoracion: null,
    efectos: ['lineas_cesped'],
    bloqueado: false,
    requisito: null,
  },
  {
    id: 'normal_gris',
    nombre: 'HIERRO',
    nivel: 1,
    color: '#888780',
    colorSecundario: '#555450',
    fondo: ['#1a1a1a', '#252525', '#181818', '#0a0a0a'],
    borde: '#888780',
    decoracion: null,
    efectos: ['rayas_metalicas'],
    bloqueado: false,
    requisito: null,
  },
  {
    id: 'normal_blanco',
    nombre: 'NIEVE',
    nivel: 1,
    color: '#cceeff',
    colorSecundario: '#aaddff',
    fondo: ['#0a1520', '#0e1e2e', '#081018', '#040a10'],
    borde: '#aaccee',
    decoracion: 'cristales',
    efectos: ['brillo_suave'],
    bloqueado: false,
    requisito: null,
  },

  // ══════════════════════════════
  // NIVEL 2 — BRONCE (10 PJ)
  // ══════════════════════════════
  {
    id: 'bronce_cobre',
    nombre: 'BRONCE',
    nivel: 2,
    color: '#cd7f32',
    colorSecundario: '#8b4a1a',
    fondo: ['#3d1e00', '#5a2d00', '#3d1e00', '#1a0c00'],
    borde: '#cd7f32',
    decoracion: 'corona_pequeña',
    efectos: ['brillo_diagonal'],
    bloqueado: true,
    requisito: '10 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 10,
  },
  {
    id: 'bronce_naranja',
    nombre: 'FUEGO SUAVE',
    nivel: 2,
    color: '#ff7800',
    colorSecundario: '#cc4400',
    fondo: ['#3d1400', '#5a1e00', '#3d1400', '#1a0800'],
    borde: '#ff7800',
    decoracion: 'chispas',
    efectos: ['rayas_diagonales'],
    bloqueado: true,
    requisito: '10 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 10,
  },
  {
    id: 'bronce_terracota',
    nombre: 'TIERRA',
    nivel: 2,
    color: '#b45014',
    colorSecundario: '#7a3000',
    fondo: ['#3d1200', '#5a1800', '#3d1200', '#180600'],
    borde: '#b45014',
    decoracion: 'hojas',
    efectos: ['textura_tierra'],
    bloqueado: true,
    requisito: '10 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 10,
  },
  {
    id: 'bronce_arena',
    nombre: 'DESIERTO',
    nivel: 2,
    color: '#d29650',
    colorSecundario: '#a06020',
    fondo: ['#3d2e00', '#5a4400', '#3d2e00', '#1a1400'],
    borde: '#d29650',
    decoracion: 'puntos',
    efectos: ['brillo_suave'],
    bloqueado: true,
    requisito: '10 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 10,
  },
  {
    id: 'bronce_oxido',
    nombre: 'HERRUMBRE',
    nivel: 2,
    color: '#a03c0a',
    colorSecundario: '#6a2000',
    fondo: ['#2e1000', '#441800', '#2e1000', '#140600'],
    borde: '#a03c0a',
    decoracion: null,
    efectos: ['textura_oxido', 'rayas_metalicas'],
    bloqueado: true,
    requisito: '10 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 10,
  },

  // ══════════════════════════════
  // NIVEL 3 — PLATA (25 PJ)
  // ══════════════════════════════
  {
    id: 'plata_acero',
    nombre: 'ACERO',
    nivel: 3,
    color: '#c0c0c0',
    colorSecundario: '#808080',
    fondo: ['#1a2030', '#242e42', '#1a2030', '#0e1420'],
    borde: '#c0c0c0',
    decoracion: 'estrellas_pequeñas',
    efectos: ['brillo_metalico', 'rayas_metalicas'],
    bloqueado: true,
    requisito: '25 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 25,
  },
  {
    id: 'plata_cyan',
    nombre: 'HIELO',
    nivel: 3,
    color: '#00c8dc',
    colorSecundario: '#008899',
    fondo: ['#003040', '#004458', '#003040', '#001820'],
    borde: '#00c8dc',
    decoracion: 'cristales',
    efectos: ['brillo_suave', 'ondas_suaves'],
    bloqueado: true,
    requisito: '25 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 25,
  },
  {
    id: 'plata_celeste',
    nombre: 'CIELO',
    nivel: 3,
    color: '#64a0ff',
    colorSecundario: '#3366cc',
    fondo: ['#0e1e40', '#162a58', '#0e1e40', '#080e20'],
    borde: '#64a0ff',
    decoracion: 'nubes',
    efectos: ['brillo_suave'],
    bloqueado: true,
    requisito: '25 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 25,
  },
  {
    id: 'plata_lila',
    nombre: 'AMATISTA',
    nivel: 3,
    color: '#b464ff',
    colorSecundario: '#7722cc',
    fondo: ['#1a0038', '#260050', '#1a0038', '#0e0020'],
    borde: '#b464ff',
    decoracion: 'gemas',
    efectos: ['ondas_suaves', 'brillo_diagonal'],
    bloqueado: true,
    requisito: '25 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 25,
  },
  {
    id: 'plata_rosa',
    nombre: 'SAKURA',
    nivel: 3,
    color: '#ff78b4',
    colorSecundario: '#cc4488',
    fondo: ['#2e0022', '#420032', '#2e0022', '#180010'],
    borde: '#ff78b4',
    decoracion: 'flores',
    efectos: ['brillo_suave'],
    bloqueado: true,
    requisito: '25 PJ jugados',
    progreso_key: 'pj',
    progreso_meta: 25,
  },

  // ══════════════════════════════
  // NIVEL 4 — ORO (1 título)
  // ══════════════════════════════
  {
    id: 'oro_campeon',
    nombre: 'CAMPEÓN',
    nivel: 4,
    color: '#ffd700',
    colorSecundario: '#aa8800',
    fondo: ['#3d2800', '#5a3c00', '#3d2800', '#1a1400'],
    borde: '#ffd700',
    decoracion: 'corona_grande',
    efectos: ['brillo_diagonal', 'rayas_diagonales'],
    bloqueado: true,
    requisito: '1 título ganado',
    progreso_key: 'titulos',
    progreso_meta: 1,
  },
  {
    id: 'oro_solar',
    nombre: 'SOLAR',
    nivel: 4,
    color: '#ffaa00',
    colorSecundario: '#cc6600',
    fondo: ['#3d2000', '#5a2e00', '#3d2000', '#1a0e00'],
    borde: '#ffaa00',
    decoracion: 'rayos_sol',
    efectos: ['rayas_diagonales', 'brillo_diagonal'],
    bloqueado: true,
    requisito: '1 título ganado',
    progreso_key: 'titulos',
    progreso_meta: 1,
  },
  {
    id: 'oro_champagne',
    nombre: 'ÉLITE',
    nivel: 4,
    color: '#ffe696',
    colorSecundario: '#ccaa44',
    fondo: ['#3d3000', '#524200', '#3d3000', '#1e1800'],
    borde: '#ffe696',
    decoracion: 'burbujas',
    efectos: ['brillo_suave', 'ondas_suaves'],
    bloqueado: true,
    requisito: '1 título ganado',
    progreso_key: 'titulos',
    progreso_meta: 1,
  },
  {
    id: 'oro_laurel',
    nombre: 'LAUREL',
    nivel: 4,
    color: '#c8a000',
    colorSecundario: '#886600',
    fondo: ['#242800', '#303600', '#242800', '#101400'],
    borde: '#c8a000',
    decoracion: 'hojas_laurel',
    efectos: ['brillo_diagonal'],
    bloqueado: true,
    requisito: '1 título ganado',
    progreso_key: 'titulos',
    progreso_meta: 1,
  },
  {
    id: 'oro_trofeo',
    nombre: 'TROFEO',
    nivel: 4,
    color: '#ffc832',
    colorSecundario: '#cc9900',
    fondo: ['#382600', '#4e3400', '#382600', '#1a1200'],
    borde: '#ffc832',
    decoracion: 'trofeo',
    efectos: ['ondas_suaves', 'brillo_diagonal', 'rayas_diagonales'],
    bloqueado: true,
    requisito: '1 título ganado',
    progreso_key: 'titulos',
    progreso_meta: 1,
  },

  // ══════════════════════════════
  // NIVEL 5 — ÉLITE (3 títulos)
  // ══════════════════════════════
  {
    id: 'elite_realeza',
    nombre: 'REALEZA',
    nivel: 5,
    color: '#9955ff',
    colorSecundario: '#5500cc',
    fondo: ['#1e0040', '#2c0060', '#1e0040', '#0e0020'],
    borde: '#9955ff',
    decoracion: 'alas_corona',
    efectos: ['ondas_suaves', 'brillo_diagonal', 'rayas_diagonales'],
    bloqueado: true,
    requisito: '3 títulos ganados',
    progreso_key: 'titulos',
    progreso_meta: 3,
  },
  {
    id: 'elite_sangre',
    nombre: 'SANGRE',
    nivel: 5,
    color: '#ff3250',
    colorSecundario: '#aa0020',
    fondo: ['#3d0010', '#5a0018', '#3d0010', '#1a0008'],
    borde: '#ff3250',
    decoracion: 'llamas_pequeñas',
    efectos: ['rayas_diagonales', 'brillo_diagonal'],
    bloqueado: true,
    requisito: '3 títulos ganados',
    progreso_key: 'titulos',
    progreso_meta: 3,
  },
  {
    id: 'elite_rayo',
    nombre: 'RAYO',
    nivel: 5,
    color: '#00b4ff',
    colorSecundario: '#0066cc',
    fondo: ['#001e40', '#002c5a', '#001e40', '#000e20'],
    borde: '#00b4ff',
    decoracion: 'rayos_electricos',
    efectos: ['brillo_diagonal', 'ondas_suaves'],
    bloqueado: true,
    requisito: '3 títulos ganados',
    progreso_key: 'titulos',
    progreso_meta: 3,
  },
  {
    id: 'elite_matrix',
    nombre: 'MATRIX',
    nivel: 5,
    color: '#00ff96',
    colorSecundario: '#00aa55',
    fondo: ['#001e10', '#002c18', '#001e10', '#000e08'],
    borde: '#00ff96',
    decoracion: 'codigo_digital',
    efectos: ['lineas_matrix', 'brillo_diagonal'],
    bloqueado: true,
    requisito: '3 títulos ganados',
    progreso_key: 'titulos',
    progreso_meta: 3,
  },
  {
    id: 'elite_cyber',
    nombre: 'CYBER',
    nivel: 5,
    color: '#ff00c8',
    colorSecundario: '#aa0088',
    fondo: ['#2e0028', '#420038', '#2e0028', '#160014'],
    borde: '#ff00c8',
    decoracion: 'circulos_cyber',
    efectos: ['grid_tech', 'brillo_diagonal'],
    bloqueado: true,
    requisito: '3 títulos ganados',
    progreso_key: 'titulos',
    progreso_meta: 3,
  },

  // ══════════════════════════════
  // NIVEL 6 — LEYENDA (5 títulos + 100 PJ)
  // ══════════════════════════════
  {
    id: 'leyenda_infierno',
    nombre: 'INFIERNO',
    nivel: 6,
    color: '#ff8800',
    colorSecundario: '#ff4400',
    colorTerciario: '#ffcc00',
    fondo: ['#3d0c00', '#5a1200', '#3d0c00', '#1a0500'],
    borde: 'gradiente_fuego',
    decoracion: 'llamas_grandes_rayos',
    efectos: ['rayas_diagonales', 'brillo_diagonal', 'particulas'],
    bloqueado: true,
    requisito: '5 títulos + 100 PJ',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
  {
    id: 'leyenda_cosmos',
    nombre: 'COSMOS',
    nivel: 6,
    color: '#9955ff',
    colorSecundario: '#4400cc',
    fondo: ['#04000e', '#0a0020', '#06000e', '#000004'],
    borde: 'gradiente_galaxia',
    decoracion: 'estrellas_nebulosa',
    efectos: ['particulas', 'brillo_diagonal'],
    bloqueado: true,
    requisito: '5 títulos + 100 PJ',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
  {
    id: 'leyenda_cristal',
    nombre: 'CRISTAL',
    nivel: 6,
    color: '#e0f4ff',
    colorSecundario: '#aaddff',
    fondo: ['#081830', '#0e2244', '#081830', '#040c18'],
    borde: 'gradiente_diamante',
    decoracion: 'gemas_destellos',
    efectos: ['brillo_suave', 'cristales', 'particulas'],
    bloqueado: true,
    requisito: '5 títulos + 100 PJ',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
  {
    id: 'leyenda_spectrum',
    nombre: 'SPECTRUM',
    nivel: 6,
    color: '#ffffff',
    colorSecundario: '#ff8800',
    fondo: ['#140020', '#1e0030', '#140020', '#080010'],
    borde: 'gradiente_arcoiris',
    decoracion: 'arcoiris_destellos',
    efectos: ['particulas', 'brillo_diagonal', 'ondas_suaves'],
    bloqueado: true,
    requisito: '5 títulos + 100 PJ',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
  {
    id: 'leyenda_icon',
    nombre: 'ICON',
    nivel: 6,
    color: '#ffd700',
    colorSecundario: '#ff8800',
    fondo: ['#1a1400', '#0a0800', '#1a1400', '#000000'],
    borde: 'gradiente_negro_oro',
    decoracion: 'corona_alas_llamas',
    efectos: ['particulas', 'brillo_diagonal', 'rayas_diagonales', 'ondas_suaves'],
    bloqueado: true,
    requisito: '5 títulos + 100 PJ',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
  {
    id: 'premium',
    nombre: 'PREMIUM',
    nivel: 6,
    color: '#D6B65D',
    colorSecundario: '#F4E6A1',
    fondo: ['#0D2B8E', '#091F7A', '#071660', '#040E40'],
    borde: 'gradiente_negro_oro',
    decoracion: null,
    efectos: [],
    premium: true,
    bloqueado: true,
    requisito: '5 títulos + 100 PJ',
    progreso_key: 'leyenda',
    progreso_meta: 1,
  },
]

export const NIVEL_NOMBRES = {
  1: 'NORMAL',
  2: 'BRONCE',
  3: 'PLATA',
  4: 'ORO',
  5: 'ÉLITE',
  6: 'LEYENDA',
}

export const NIVEL_COLORES = {
  1: '#00ddd0',
  2: '#cd7f32',
  3: '#c0c0c0',
  4: '#ffd700',
  5: '#9955ff',
  6: '#ff8800',
}

